name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }}  | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build Docker image
        run: docker build -t ngo-backend ./backend

      - name: Tag image
        run: docker tag ngo-backend:latest ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push to ECR
        run: docker push ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: PORT,MONGO_URI,RAZORPAY_KEY,RAZORPAY_SECRET
          script: |
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -aq) || true
      
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 657566734867.dkr.ecr.ap-south-1.amazonaws.com
      
            docker pull ${{ secrets.ECR_REPOSITORY }}:latest
      
            docker run -d -p 3000:3000 \
            -e PORT=$PORT \
            -e MONGO_URI=$MONGO_URI \
            -e RAZORPAY_KEY=$RAZORPAY_KEY \
            -e RAZORPAY_SECRET=$RAZORPAY_SECRET \
            ${{ secrets.ECR_REPOSITORY }}:latest
